[package]
name = "minter-export"
version = "0.1.0"
authors = ["Nicolas KOWALSKI <kowalski.kowalskin@gmail.com>"]
edition = "2018"
description = "Messages for the minter contract (migrator)"

[lib]
bench = false

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
# CosmWasm
cw721-base = "0.13.0"
cw-storage-plus = "0.13.0"
cw20-base = { version = "0.13.0", features = ["library"] }
cosmwasm-std = { version = "1.0.0" }

#Other Modules
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.23" }
strum = "0.24"
strum_macros = "0.24"

#Local Modules

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0" }

